name: Cloud Run

on:
  push:
  workflow_dispatch:

concurrency: ${{ github.ref }}

env:
  IMAGE: us-docker.pkg.dev/${{vars.GCP_PROJECT}}/us.gcr.io/${{ github.event.repository.name }}:${{ github.ref_name }}

  SERVICE: ${{ github.event.repository.name }}-${{ github.ref_name }}
  PUBLIC_URL: https://${{ github.event.repository.name }}-${{ github.ref_name }}-${{secrets.GCP_RUN_TOKEN}}-uc.a.run.app

  REGION: us-central1
  GCP_SA: chienle-sa@${{vars.GCP_PROJECT}}.iam.gserviceaccount.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: docker/setup-buildx-action@v2
        with:
          install: true

      - uses: google-github-actions/setup-gcloud@v2

      - run: gcloud auth configure-docker us-docker.pkg.dev

      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE }}

      - run: >-
          gcloud run deploy ${{ env.SERVICE }}
          --image=${{ env.IMAGE }}
          --memory=8Gi
          --cpu=2
          --platform=managed
          --service-account=${{ env.GCP_SA }}
          --region=${{ env.REGION }}
          --timeout=3500
          --set-env-vars=PUBLIC_URL=${{ env.PUBLIC_URL }}
          --allow-unauthenticated
          --labels run-service-id=${{ env.SERVICE }}
